# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Yuanmxc/repository/MxcServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Yuanmxc/repository/MxcServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Yuanmxc/repository/MxcServer/CMakeFiles /home/Yuanmxc/repository/MxcServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Yuanmxc/repository/MxcServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Web_Server

# Build rule for target.
Web_Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Web_Server
.PHONY : Web_Server

# fast build rule for target.
Web_Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/build
.PHONY : Web_Server/fast

src/Web_Server.o: src/Web_Server.cc.o
.PHONY : src/Web_Server.o

# target to build an object file
src/Web_Server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/Web_Server.cc.o
.PHONY : src/Web_Server.cc.o

src/Web_Server.i: src/Web_Server.cc.i
.PHONY : src/Web_Server.i

# target to preprocess a source file
src/Web_Server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/Web_Server.cc.i
.PHONY : src/Web_Server.cc.i

src/Web_Server.s: src/Web_Server.cc.s
.PHONY : src/Web_Server.s

# target to generate assembly for a file
src/Web_Server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/Web_Server.cc.s
.PHONY : src/Web_Server.cc.s

src/base/Yuanmxc_Arch.o: src/base/Yuanmxc_Arch.cc.o
.PHONY : src/base/Yuanmxc_Arch.o

# target to build an object file
src/base/Yuanmxc_Arch.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/base/Yuanmxc_Arch.cc.o
.PHONY : src/base/Yuanmxc_Arch.cc.o

src/base/Yuanmxc_Arch.i: src/base/Yuanmxc_Arch.cc.i
.PHONY : src/base/Yuanmxc_Arch.i

# target to preprocess a source file
src/base/Yuanmxc_Arch.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/base/Yuanmxc_Arch.cc.i
.PHONY : src/base/Yuanmxc_Arch.cc.i

src/base/Yuanmxc_Arch.s: src/base/Yuanmxc_Arch.cc.s
.PHONY : src/base/Yuanmxc_Arch.s

# target to generate assembly for a file
src/base/Yuanmxc_Arch.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/base/Yuanmxc_Arch.cc.s
.PHONY : src/base/Yuanmxc_Arch.cc.s

src/core/contentprovide.o: src/core/contentprovide.cc.o
.PHONY : src/core/contentprovide.o

# target to build an object file
src/core/contentprovide.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/contentprovide.cc.o
.PHONY : src/core/contentprovide.cc.o

src/core/contentprovide.i: src/core/contentprovide.cc.i
.PHONY : src/core/contentprovide.i

# target to preprocess a source file
src/core/contentprovide.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/contentprovide.cc.i
.PHONY : src/core/contentprovide.cc.i

src/core/contentprovide.s: src/core/contentprovide.cc.s
.PHONY : src/core/contentprovide.s

# target to generate assembly for a file
src/core/contentprovide.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/contentprovide.cc.s
.PHONY : src/core/contentprovide.cc.s

src/core/manger.o: src/core/manger.cc.o
.PHONY : src/core/manger.o

# target to build an object file
src/core/manger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/manger.cc.o
.PHONY : src/core/manger.cc.o

src/core/manger.i: src/core/manger.cc.i
.PHONY : src/core/manger.i

# target to preprocess a source file
src/core/manger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/manger.cc.i
.PHONY : src/core/manger.cc.i

src/core/manger.s: src/core/manger.cc.s
.PHONY : src/core/manger.s

# target to generate assembly for a file
src/core/manger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/manger.cc.s
.PHONY : src/core/manger.cc.s

src/core/member.o: src/core/member.cc.o
.PHONY : src/core/member.o

# target to build an object file
src/core/member.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/member.cc.o
.PHONY : src/core/member.cc.o

src/core/member.i: src/core/member.cc.i
.PHONY : src/core/member.i

# target to preprocess a source file
src/core/member.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/member.cc.i
.PHONY : src/core/member.cc.i

src/core/member.s: src/core/member.cc.s
.PHONY : src/core/member.s

# target to generate assembly for a file
src/core/member.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/member.cc.s
.PHONY : src/core/member.cc.s

src/core/provider/provider.o: src/core/provider/provider.cc.o
.PHONY : src/core/provider/provider.o

# target to build an object file
src/core/provider/provider.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/provider/provider.cc.o
.PHONY : src/core/provider/provider.cc.o

src/core/provider/provider.i: src/core/provider/provider.cc.i
.PHONY : src/core/provider/provider.i

# target to preprocess a source file
src/core/provider/provider.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/provider/provider.cc.i
.PHONY : src/core/provider/provider.cc.i

src/core/provider/provider.s: src/core/provider/provider.cc.s
.PHONY : src/core/provider/provider.s

# target to generate assembly for a file
src/core/provider/provider.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/provider/provider.cc.s
.PHONY : src/core/provider/provider.cc.s

src/core/provider/reaprovider.o: src/core/provider/reaprovider.cc.o
.PHONY : src/core/provider/reaprovider.o

# target to build an object file
src/core/provider/reaprovider.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/provider/reaprovider.cc.o
.PHONY : src/core/provider/reaprovider.cc.o

src/core/provider/reaprovider.i: src/core/provider/reaprovider.cc.i
.PHONY : src/core/provider/reaprovider.i

# target to preprocess a source file
src/core/provider/reaprovider.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/provider/reaprovider.cc.i
.PHONY : src/core/provider/reaprovider.cc.i

src/core/provider/reaprovider.s: src/core/provider/reaprovider.cc.s
.PHONY : src/core/provider/reaprovider.s

# target to generate assembly for a file
src/core/provider/reaprovider.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/provider/reaprovider.cc.s
.PHONY : src/core/provider/reaprovider.cc.s

src/core/ws.o: src/core/ws.cc.o
.PHONY : src/core/ws.o

# target to build an object file
src/core/ws.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/ws.cc.o
.PHONY : src/core/ws.cc.o

src/core/ws.i: src/core/ws.cc.i
.PHONY : src/core/ws.i

# target to preprocess a source file
src/core/ws.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/ws.cc.i
.PHONY : src/core/ws.cc.i

src/core/ws.s: src/core/ws.cc.s
.PHONY : src/core/ws.s

# target to generate assembly for a file
src/core/ws.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/core/ws.cc.s
.PHONY : src/core/ws.cc.s

src/http/hrrpstatus.o: src/http/hrrpstatus.cc.o
.PHONY : src/http/hrrpstatus.o

# target to build an object file
src/http/hrrpstatus.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/http/hrrpstatus.cc.o
.PHONY : src/http/hrrpstatus.cc.o

src/http/hrrpstatus.i: src/http/hrrpstatus.cc.i
.PHONY : src/http/hrrpstatus.i

# target to preprocess a source file
src/http/hrrpstatus.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/http/hrrpstatus.cc.i
.PHONY : src/http/hrrpstatus.cc.i

src/http/hrrpstatus.s: src/http/hrrpstatus.cc.s
.PHONY : src/http/hrrpstatus.s

# target to generate assembly for a file
src/http/hrrpstatus.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/http/hrrpstatus.cc.s
.PHONY : src/http/hrrpstatus.cc.s

src/http/httpparser.o: src/http/httpparser.cc.o
.PHONY : src/http/httpparser.o

# target to build an object file
src/http/httpparser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/http/httpparser.cc.o
.PHONY : src/http/httpparser.cc.o

src/http/httpparser.i: src/http/httpparser.cc.i
.PHONY : src/http/httpparser.i

# target to preprocess a source file
src/http/httpparser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/http/httpparser.cc.i
.PHONY : src/http/httpparser.cc.i

src/http/httpparser.s: src/http/httpparser.cc.s
.PHONY : src/http/httpparser.s

# target to generate assembly for a file
src/http/httpparser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/http/httpparser.cc.s
.PHONY : src/http/httpparser.cc.s

src/http/httprequest.o: src/http/httprequest.cc.o
.PHONY : src/http/httprequest.o

# target to build an object file
src/http/httprequest.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/http/httprequest.cc.o
.PHONY : src/http/httprequest.cc.o

src/http/httprequest.i: src/http/httprequest.cc.i
.PHONY : src/http/httprequest.i

# target to preprocess a source file
src/http/httprequest.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/http/httprequest.cc.i
.PHONY : src/http/httprequest.cc.i

src/http/httprequest.s: src/http/httprequest.cc.s
.PHONY : src/http/httprequest.s

# target to generate assembly for a file
src/http/httprequest.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/http/httprequest.cc.s
.PHONY : src/http/httprequest.cc.s

src/net/address.o: src/net/address.cc.o
.PHONY : src/net/address.o

# target to build an object file
src/net/address.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/address.cc.o
.PHONY : src/net/address.cc.o

src/net/address.i: src/net/address.cc.i
.PHONY : src/net/address.i

# target to preprocess a source file
src/net/address.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/address.cc.i
.PHONY : src/net/address.cc.i

src/net/address.s: src/net/address.cc.s
.PHONY : src/net/address.s

# target to generate assembly for a file
src/net/address.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/address.cc.s
.PHONY : src/net/address.cc.s

src/net/server.o: src/net/server.cc.o
.PHONY : src/net/server.o

# target to build an object file
src/net/server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/server.cc.o
.PHONY : src/net/server.cc.o

src/net/server.i: src/net/server.cc.i
.PHONY : src/net/server.i

# target to preprocess a source file
src/net/server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/server.cc.i
.PHONY : src/net/server.cc.i

src/net/server.s: src/net/server.cc.s
.PHONY : src/net/server.s

# target to generate assembly for a file
src/net/server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/server.cc.s
.PHONY : src/net/server.cc.s

src/net/socket.o: src/net/socket.cc.o
.PHONY : src/net/socket.o

# target to build an object file
src/net/socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/socket.cc.o
.PHONY : src/net/socket.cc.o

src/net/socket.i: src/net/socket.cc.i
.PHONY : src/net/socket.i

# target to preprocess a source file
src/net/socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/socket.cc.i
.PHONY : src/net/socket.cc.i

src/net/socket.s: src/net/socket.cc.s
.PHONY : src/net/socket.s

# target to generate assembly for a file
src/net/socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/socket.cc.s
.PHONY : src/net/socket.cc.s

src/net/writeloop.o: src/net/writeloop.cc.o
.PHONY : src/net/writeloop.o

# target to build an object file
src/net/writeloop.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/writeloop.cc.o
.PHONY : src/net/writeloop.cc.o

src/net/writeloop.i: src/net/writeloop.cc.i
.PHONY : src/net/writeloop.i

# target to preprocess a source file
src/net/writeloop.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/writeloop.cc.i
.PHONY : src/net/writeloop.cc.i

src/net/writeloop.s: src/net/writeloop.cc.s
.PHONY : src/net/writeloop.s

# target to generate assembly for a file
src/net/writeloop.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/net/writeloop.cc.s
.PHONY : src/net/writeloop.cc.s

src/tool/fileproxy.o: src/tool/fileproxy.cc.o
.PHONY : src/tool/fileproxy.o

# target to build an object file
src/tool/fileproxy.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/fileproxy.cc.o
.PHONY : src/tool/fileproxy.cc.o

src/tool/fileproxy.i: src/tool/fileproxy.cc.i
.PHONY : src/tool/fileproxy.i

# target to preprocess a source file
src/tool/fileproxy.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/fileproxy.cc.i
.PHONY : src/tool/fileproxy.cc.i

src/tool/fileproxy.s: src/tool/fileproxy.cc.s
.PHONY : src/tool/fileproxy.s

# target to generate assembly for a file
src/tool/fileproxy.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/fileproxy.cc.s
.PHONY : src/tool/fileproxy.cc.s

src/tool/filereader.o: src/tool/filereader.cc.o
.PHONY : src/tool/filereader.o

# target to build an object file
src/tool/filereader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/filereader.cc.o
.PHONY : src/tool/filereader.cc.o

src/tool/filereader.i: src/tool/filereader.cc.i
.PHONY : src/tool/filereader.i

# target to preprocess a source file
src/tool/filereader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/filereader.cc.i
.PHONY : src/tool/filereader.cc.i

src/tool/filereader.s: src/tool/filereader.cc.s
.PHONY : src/tool/filereader.s

# target to generate assembly for a file
src/tool/filereader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/filereader.cc.s
.PHONY : src/tool/filereader.cc.s

src/tool/parsed_header.o: src/tool/parsed_header.cc.o
.PHONY : src/tool/parsed_header.o

# target to build an object file
src/tool/parsed_header.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/parsed_header.cc.o
.PHONY : src/tool/parsed_header.cc.o

src/tool/parsed_header.i: src/tool/parsed_header.cc.i
.PHONY : src/tool/parsed_header.i

# target to preprocess a source file
src/tool/parsed_header.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/parsed_header.cc.i
.PHONY : src/tool/parsed_header.cc.i

src/tool/parsed_header.s: src/tool/parsed_header.cc.s
.PHONY : src/tool/parsed_header.s

# target to generate assembly for a file
src/tool/parsed_header.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/parsed_header.cc.s
.PHONY : src/tool/parsed_header.cc.s

src/tool/timing_wheel.o: src/tool/timing_wheel.cc.o
.PHONY : src/tool/timing_wheel.o

# target to build an object file
src/tool/timing_wheel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/timing_wheel.cc.o
.PHONY : src/tool/timing_wheel.cc.o

src/tool/timing_wheel.i: src/tool/timing_wheel.cc.i
.PHONY : src/tool/timing_wheel.i

# target to preprocess a source file
src/tool/timing_wheel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/timing_wheel.cc.i
.PHONY : src/tool/timing_wheel.cc.i

src/tool/timing_wheel.s: src/tool/timing_wheel.cc.s
.PHONY : src/tool/timing_wheel.s

# target to generate assembly for a file
src/tool/timing_wheel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/timing_wheel.cc.s
.PHONY : src/tool/timing_wheel.cc.s

src/tool/userbuffer.o: src/tool/userbuffer.cc.o
.PHONY : src/tool/userbuffer.o

# target to build an object file
src/tool/userbuffer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/userbuffer.cc.o
.PHONY : src/tool/userbuffer.cc.o

src/tool/userbuffer.i: src/tool/userbuffer.cc.i
.PHONY : src/tool/userbuffer.i

# target to preprocess a source file
src/tool/userbuffer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/userbuffer.cc.i
.PHONY : src/tool/userbuffer.cc.i

src/tool/userbuffer.s: src/tool/userbuffer.cc.s
.PHONY : src/tool/userbuffer.s

# target to generate assembly for a file
src/tool/userbuffer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Web_Server.dir/build.make CMakeFiles/Web_Server.dir/src/tool/userbuffer.cc.s
.PHONY : src/tool/userbuffer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Web_Server"
	@echo "... src/Web_Server.o"
	@echo "... src/Web_Server.i"
	@echo "... src/Web_Server.s"
	@echo "... src/base/Yuanmxc_Arch.o"
	@echo "... src/base/Yuanmxc_Arch.i"
	@echo "... src/base/Yuanmxc_Arch.s"
	@echo "... src/core/contentprovide.o"
	@echo "... src/core/contentprovide.i"
	@echo "... src/core/contentprovide.s"
	@echo "... src/core/manger.o"
	@echo "... src/core/manger.i"
	@echo "... src/core/manger.s"
	@echo "... src/core/member.o"
	@echo "... src/core/member.i"
	@echo "... src/core/member.s"
	@echo "... src/core/provider/provider.o"
	@echo "... src/core/provider/provider.i"
	@echo "... src/core/provider/provider.s"
	@echo "... src/core/provider/reaprovider.o"
	@echo "... src/core/provider/reaprovider.i"
	@echo "... src/core/provider/reaprovider.s"
	@echo "... src/core/ws.o"
	@echo "... src/core/ws.i"
	@echo "... src/core/ws.s"
	@echo "... src/http/hrrpstatus.o"
	@echo "... src/http/hrrpstatus.i"
	@echo "... src/http/hrrpstatus.s"
	@echo "... src/http/httpparser.o"
	@echo "... src/http/httpparser.i"
	@echo "... src/http/httpparser.s"
	@echo "... src/http/httprequest.o"
	@echo "... src/http/httprequest.i"
	@echo "... src/http/httprequest.s"
	@echo "... src/net/address.o"
	@echo "... src/net/address.i"
	@echo "... src/net/address.s"
	@echo "... src/net/server.o"
	@echo "... src/net/server.i"
	@echo "... src/net/server.s"
	@echo "... src/net/socket.o"
	@echo "... src/net/socket.i"
	@echo "... src/net/socket.s"
	@echo "... src/net/writeloop.o"
	@echo "... src/net/writeloop.i"
	@echo "... src/net/writeloop.s"
	@echo "... src/tool/fileproxy.o"
	@echo "... src/tool/fileproxy.i"
	@echo "... src/tool/fileproxy.s"
	@echo "... src/tool/filereader.o"
	@echo "... src/tool/filereader.i"
	@echo "... src/tool/filereader.s"
	@echo "... src/tool/parsed_header.o"
	@echo "... src/tool/parsed_header.i"
	@echo "... src/tool/parsed_header.s"
	@echo "... src/tool/timing_wheel.o"
	@echo "... src/tool/timing_wheel.i"
	@echo "... src/tool/timing_wheel.s"
	@echo "... src/tool/userbuffer.o"
	@echo "... src/tool/userbuffer.i"
	@echo "... src/tool/userbuffer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

